# Generated by Django 5.2.6 on 2025-11-14 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='badge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='website.badge'),
        ),
    ]
