# Generated by Django 5.2.6 on 2025-11-05 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access the course when visibility is set to PRIVATE', related_name='course_access', through='website.UserCourseAccessLevel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'PUBLIC'), ('PRI', 'PRIVATE')], default='PRI', max_length=50),
        ),
        migrations.AlterField(
            model_name='progressoftask',
            name='status',
            field=models.CharField(choices=[('NOSTAR', 'NOT STARTED'), ('INCOMP', 'INCOMPLETE'), ('COMPLE', 'COMPLETED')], default='NOSTAR', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='access_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access the room when visibility is set to PRIVATE', related_name='room_access', through='website.UserRoomAccessLevel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'PUBLIC'), ('PRI', 'PRIVATE')], default='PRI', max_length=50),
        ),
        migrations.AlterField(
            model_name='savedtask',
            name='status',
            field=models.CharField(choices=[('NOSTAR', 'NOT STARTED'), ('INCOMP', 'INCOMPLETE'), ('COMPLE', 'COMPLETED')], default='NOSTAR', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='access_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access the section when visibility is set to PRIVATE', related_name='section_access', through='website.UserSectionAccessLevel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'PUBLIC'), ('PRI', 'PRIVATE')], default='PRI', max_length=50),
        ),
        migrations.AlterField(
            model_name='usercourseaccesslevel',
            name='access_level',
            field=models.CharField(choices=[('ED', 'EDITOR'), ('VI', 'VISITOR')], default='VI', max_length=50),
        ),
        migrations.AlterField(
            model_name='userroomaccesslevel',
            name='access_level',
            field=models.CharField(choices=[('ED', 'EDITOR'), ('VI', 'VISITOR')], default='VI', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersectionaccesslevel',
            name='access_level',
            field=models.CharField(choices=[('ED', 'EDITOR'), ('VI', 'VISITOR')], default='VI', max_length=50),
        ),
    ]
