# Generated by Django 5.2.6 on 2025-12-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='number_of_problems',
        ),
        migrations.RemoveField(
            model_name='section',
            name='number_of_problems',
        ),
        migrations.AlterField(
            model_name='course',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'PUBLIC'), ('PRI', 'PRIVATE')], default='PUB', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'PUBLIC'), ('PRI', 'PRIVATE')], default='PUB', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskcomponent',
            name='type',
            field=models.CharField(choices=[('OPTION', 'MULTIPLE CHOICE OPTION'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('TEXT', 'TEXT'), ('FILL', 'FILL IN THE BLANK QUESTION'), ('MATCH', 'MATCH TERM TO DEFINITION')], max_length=50),
        ),
    ]
