# Generated by Django 5.2.6 on 2025-10-13 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressofelement',
            name='element',
        ),
        migrations.RemoveField(
            model_name='savedproblem',
            name='element',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='course',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='section',
        ),
        migrations.RemoveField(
            model_name='progressofelement',
            name='problemset',
        ),
        migrations.RemoveField(
            model_name='savedproblem',
            name='problemset',
        ),
        migrations.RemoveField(
            model_name='progressofelement',
            name='course',
        ),
        migrations.RemoveField(
            model_name='progressofelement',
            name='section',
        ),
        migrations.RemoveField(
            model_name='progressofelement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedproblem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='savedproblem',
            name='section',
        ),
        migrations.RemoveField(
            model_name='savedproblem',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='visibility',
            field=models.CharField(choices=[('PRI', 'PRIVATE'), ('PUB', 'PUBLIC'), ('LIM', 'LIMITER')], default='PRI', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='visibility',
            field=models.CharField(choices=[('PRI', 'PRIVATE'), ('PUB', 'PUBLIC'), ('LIM', 'LIMITER')], default='PRI', max_length=50),
        ),
        migrations.AlterField(
            model_name='usercourseaccesslevel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.course'),
        ),
        migrations.AlterField(
            model_name='usercourseaccesslevel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersectionaccesslevel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.course'),
        ),
        migrations.AlterField(
            model_name='usersectionaccesslevel',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.section'),
        ),
        migrations.AlterField(
            model_name='usersectionaccesslevel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('PRI', 'PRIVATE'), ('PUB', 'PUBLIC'), ('LIM', 'LIMITER')], default='PRI', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='website.course')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='website.section')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('point_value', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='website.room')),
                ('tags', models.ManyToManyField(to='website.tag')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOSTAR', 'NOT STARTED'), ('INPROG', 'IN-PROGRESS'), ('COMPLE', 'COMPLETED')], default='NOSTAR', max_length=50)),
                ('saved_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.course')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.room')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.section')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.task')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressOfTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOSTAR', 'NOT STARTED'), ('INPROG', 'IN-PROGRESS'), ('COMPLE', 'COMPLETED')], default='NOSTAR', max_length=50)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.course')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.section')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.room')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('type', models.CharField(choices=[('OPTION', 'MULTIPLE CHOICE OPTION'), ('IMAGE', 'IMAGE'), ('TEXT', 'TEXT'), ('FILL', 'FILL IN THE BLANK QUESTION')], max_length=50)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='website.task')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoomAccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('AD', 'ADMIN'), ('VI', 'VISITOR')], default='VI', max_length=50)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.course')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.room')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.section')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='access_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access the room when visibility is set to LIMITER', related_name='room_access', through='website.UserRoomAccessLevel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='ProblemSet',
        ),
        migrations.DeleteModel(
            name='ProgressOfElement',
        ),
        migrations.DeleteModel(
            name='SavedProblem',
        ),
    ]
