# Generated by Django 5.2.6 on 2025-12-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_room_number_of_problems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='language',
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='DictionaryEntry',
        ),
    ]
