# Generated by Django 5.2.6 on 2025-12-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_dictionaryentry_language_delete_dictionary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messege', models.CharField(max_length=1000)),
                ('reported_object', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
