# Generated by Django 5.2.6 on 2025-11-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
    ]
