# Generated by Django 5.2.6 on 2025-12-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reported_object',
            new_name='reported_obj',
        ),
    ]
