# Generated by Django 5.2.6 on 2026-01-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_historicalcourse_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'PUBLIC'), ('PEN', 'PENDING'), ('PRI', 'PRIVATE')], default='PUB', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'PUBLIC'), ('PEN', 'PENDING'), ('PRI', 'PRIVATE')], default='PRI', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'PUBLIC'), ('PEN', 'PENDING'), ('PRI', 'PRIVATE')], default='PUB', max_length=50),
        ),
    ]
