import { Link, useLocation } from "react-router-dom";
import { Menu, Search } from "lucide-react"; 
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input"; 
import {
  Sheet,
  SheetContent,
  SheetTrigger,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "@/components/ui/sheet";

//IMPORTANT: Comments are generated by AI to improve code readability and maintainability.

// Define custom styles and colors for easy modification and clarity
const zalandoFont = { fontFamily: "'Zalando Sans Expanded', sans-serif" };
const vivanYellow = '#FDD023';

const navLinks = [
  { path: "/login", label: "LOGIN/SIGNUP" }, 
  { path: "/courses", label: "COURSES" },
  { path: "/create", label: "CREATE" }, 
  { path: "/", label: "HOME" },
  { path: "/about", label: "ABOUT" },
  { path: "/contact", label: "CONTACT" },
];

export default function Navbar() {
  const location = useLocation();

  /**
   * Determines if a navigation link is currently active.
   * Handles the special case for the root path ('/') to ensure exact matching.
   */
  const isActive = (path) => {
    if (path === "/") {
        // Exact match required for the Home path
        return location.pathname === "/"; 
    }
    // For other paths (e.g., /courses), check if the pathname starts with the link path
    return location.pathname.startsWith(path);
  };

  const BrandLogo = (
    <Link to="/" className="flex items-center">
      <h1
        className="text-3xl font-bold"
        style={{ fontFamily: "'Lobster Two', cursive", color: vivanYellow }}
      >
        vivan
      </h1>
    </Link>
  );

  return (
    <nav className="w-full bg-[#023B4E] fixed top-0 left-0 right-0 z-50">
      
      {/* Main Layout Container:
        - w-full: Spans the entire viewport width.
        - px-*: Provides consistent padding from the viewport edges on all screens (mobile/desktop).
        - grid-cols-[auto_1fr_auto]: This is the key responsive fix.
          - 'auto': Column 1 (Logo) takes only required width.
          - '1fr': Column 2 (Links) takes all available remaining space.
          - 'auto': Column 3 (Menu) takes only required width.
        This forces the Logo and Menu button to stick to the far left/right edges (minus padding).
      */}
      <div className="w-full min-h-[60px] px-4 md:px-6 lg:px-8 
                    grid grid-cols-[auto_1fr_auto] items-center"> 
        
        {/* 1. Logo/Brand - Fixed Left */}
        <div className="justify-self-start">
            {BrandLogo}
        </div>

        {/* Desktop links - hidden on narrower devices */}
        {/* The links are centered (mx-auto) within the wide 1fr middle column (justify-self-center). */}
        <div className="hidden md:flex justify-self-center mx-auto max-w-7xl">
            <ul className="flex items-center gap-8">
            {navLinks.map((link) => (
                <li key={link.path}>
                <Link
                    to={link.path}
                    className={`font-medium transition-colors text-sm uppercase 
                        ${isActive(link.path)
                        // Use vivanYellow for active link
                        ? `text-[${vivanYellow}]`
                        // Use white text, hover to vivanYellow
                        : "text-white hover:text-[#FDD023]"
                    }`}
                    style={zalandoFont} // Apply custom font
                >
                    {link.label}
                </Link>
                </li>
            ))}
            </ul>
        </div>

        {/* Locking Hamburger icon towards the right */}
        <div className="justify-self-end">
            <Sheet>
                <SheetTrigger asChild>
                    <Button 
                        variant="ghost" 
                        size="icon" 
                        className="text-white hover:text-[#FDD023] hover:bg-transparent"
                        aria-label="Open Mobile Menu"
                    >
                        <Menu size={28} />
                    </Button>
                </SheetTrigger>

                {/* --- Mobile Menu Content (Sidebar) --- */}
                <SheetContent 
                    side="right" 
                    // Final Sidebar Dimensions and Internal Padding
                    className="w-[300px] sm:w-[380px] px-10 pt-10" 
                    style={zalandoFont} // Apply custom font to all sidebar content
                >
                    <SheetHeader>
                        {/* Title: text-xl, font-bold, -ml-3 for perfect left alignment */}
                        <SheetTitle className="text-xl font-bold text-foreground text-left -ml-3">Menu</SheetTitle> 
                        
                        {/* Description: text-sm, normal weight, mt-2 for vertical spacing, -ml-3 for alignment */}
                        <SheetDescription className="text-sm text-muted-foreground mt-2 text-left -ml-3" style={{ fontWeight: 400 }}>
                            Navigate through Vivan
                        </SheetDescription>
                    </SheetHeader>
                    
                    {/* Search Bar: my-6 for consistent vertical spacing */}
                    <div className="relative my-6"> 
                        <Search className="absolute left-2 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                        <Input 
                            type="search" 
                            placeholder="Search friends or courses..." 
                            className="w-full pl-8" 
                        />
                    </div>
                    
                    {/* Mobile Links: Increased font size (text-lg), tight gap (gap-4), mt-6 margin from search bar */}
                    <nav className="flex flex-col gap-4 mt-6"> 
                        {navLinks.map((link) => (
                            <Link
                                key={link.path}
                                to={link.path}
                                onClick={() => document.getElementById('sheet-close')?.click()}
                                className={`font-bold text-lg uppercase transition-colors text-left
                                    ${isActive(link.path) 
                                        // Active Link: Use custom yellow color, else normal black color without hover effect
                                        ? `text-[${vivanYellow}]`
                                        : "text-foreground hover:text-[#FDD023]" 
                                }`}
                            >
                                {link.label}
                            </Link>
                        ))}
                    </nav>
                </SheetContent>
            </Sheet>
        </div>
      </div>
    </nav>
  );
}