# Generated by Django 5.2.6 on 2026-01-14 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'managed': False, 'ordering': ['headword']},
        ),
        migrations.AlterModelOptions(
            name='pos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'managed': False},
        ),
    ]
