# Generated by Django 5.2.6 on 2025-12-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_historicaldefinition_historicalentry_historicalpos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'managed': False, 'ordering': ['headword']},
        ),
    ]
