# Generated by Django 5.2.6 on 2025-09-20 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('visibility', models.CharField(choices=[('PRI', 'PRIVATE'), ('PUB', 'PUBLIC'), ('LIM', 'LIMITER')], default='PUB', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.course')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=200)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('number_of_problems', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemsets', to='website.course')),
            ],
        ),
        migrations.CreateModel(
            name='PointlessElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(blank=True, default=dict)),
                ('interface_data', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('problemset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointless_elements', to='website.problemset')),
            ],
        ),
        migrations.CreateModel(
            name='PointElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(blank=True, default=dict)),
                ('type', models.CharField(choices=[('MCQ', 'MULTIPLE CHOICE QUESTION'), ('FREE', 'FREE RESPONSE QUESTION')], max_length=50)),
                ('point_value', models.IntegerField(default=1)),
                ('interface_data', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('problemset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_elements', to='website.problemset')),
                ('tags', models.ManyToManyField(to='website.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('visibility', models.CharField(choices=[('PRI', 'PRIVATE'), ('PUB', 'PUBLIC'), ('LIM', 'LIMITER')], default='PUB', max_length=50)),
                ('number_of_problems', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='website.course')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sections', to='website.user')),
            ],
        ),
        migrations.AddField(
            model_name='problemset',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemsets', to='website.section'),
        ),
        migrations.CreateModel(
            name='SavedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOSTAR', 'NOT STARTED'), ('INPROG', 'IN-PROGRESS'), ('COMPLE', 'COMPLETED')], default='NOSTAR', max_length=50)),
                ('saved_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.course')),
                ('pointelement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.pointelement')),
                ('problemset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.problemset')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.section')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressOfProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOSTAR', 'NOT STARTED'), ('INPROG', 'IN-PROGRESS'), ('COMPLE', 'COMPLETED')], default='NOSTAR', max_length=50)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.course')),
                ('problemset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.problemset')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.section')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user')),
            ],
        ),
        migrations.AddField(
            model_name='problemset',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problemsets', to='website.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to='website.user'),
        ),
        migrations.CreateModel(
            name='UserCourseAccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('AD', 'ADMIN'), ('VI', 'VISITOR')], default='VI', max_length=50)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='access_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access the course when visibility is set to LIMITER', related_name='course_access', through='website.UserCourseAccessLevel', to='website.user'),
        ),
        migrations.CreateModel(
            name='UserSectionAccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('AD', 'ADMIN'), ('VI', 'VISITOR')], default='VI', max_length=50)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.course')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.section')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='access_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access the section when visibility is set to LIMITER', related_name='section_access', through='website.UserSectionAccessLevel', to='website.user'),
        ),
    ]
